import Image from "next/image";
import Hero from "../components/Hero/Hero";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Tailwind Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      {/* Other components and content */}
    </div>
  );
}
